package earth.darkwhite.albiononlinemarketdata.ui.theme

import android.graphics.Color.rgb
import androidx.compose.ui.graphics.Color

val greenColor = Color(rgb(80, 200, 120))
val redColor = Color(rgb(227, 38, 54))

val md_theme_light_primary = Color(0xFF944837)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD2)
val md_theme_light_onPrimaryContainer = Color(0xFF3C0701)
val md_theme_light_secondary = Color(0xFF77574F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD2)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1510)
val md_theme_light_tertiary = Color(0xFF6D5D2E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF8E1A6)
val md_theme_light_onTertiaryContainer = Color(0xFF241A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF83706D)
val md_theme_light_background = Color(0xFFFFF8F6)
val md_theme_light_onBackground = Color(0xFF231917)
val md_theme_light_surface = Color(0xFFFFF8F6)
val md_theme_light_onSurface = Color(0xFF231917)
val md_theme_light_surfaceVariant = Color(0xFFF5DDD8)
val md_theme_light_onSurfaceVariant = Color(0xFF534340)
val md_theme_light_inverseSurface = Color(0xFF392E2C)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE9)
val md_theme_light_inversePrimary = Color(0xFFFFB4A3)
val md_theme_light_surfaceTint = Color(0xFF944837)
val md_theme_light_outlineVariant = Color(0xFFD8C2BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB4A3)
val md_theme_dark_onPrimary = Color(0xFF591C0E)
val md_theme_dark_primaryContainer = Color(0xFF763222)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_secondary = Color(0xFFE7BDB4)
val md_theme_dark_onSecondary = Color(0xFF442A24)
val md_theme_dark_secondaryContainer = Color(0xFF5D3F39)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_tertiary = Color(0xFFDBC58C)
val md_theme_dark_onTertiary = Color(0xFF3C2F04)
val md_theme_dark_tertiaryContainer = Color(0xFF544519)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8E1A6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF83706D)
val md_theme_dark_background = Color(0xFF1A110F)
val md_theme_dark_onBackground = Color(0xFFF1DFDB)
val md_theme_dark_surface = Color(0xFF1A110F)
val md_theme_dark_onSurface = Color(0xFFF1DFDB)
val md_theme_dark_surfaceVariant = Color(0xFF534340)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BD)
val md_theme_dark_inverseSurface = Color(0xFFF1DFDB)
val md_theme_dark_inverseOnSurface = Color(0xFF392E2C)
val md_theme_dark_inversePrimary = Color(0xFF944837)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A3)
val md_theme_dark_outlineVariant = Color(0xFF534340)
val md_theme_dark_scrim = Color(0xFF000000)


//val seed = Color(0xFF331913)
